// packages/solid/src/panel/PanelBody.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type PanelBodyProps = {
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function PanelBody(props: PanelBodyProps) {
    const [local, rest] = splitProps(props, ["class", "children"]);
    const classes = () =>
        ["govuk-panel__body", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <div class={classes()} {...rest}>
            {local.children}
        </div>
    );
}

// packages/react/src/panel/PanelBody.tsx
import { ReactNode } from 'react';

type PanelBodyProps = {
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function PanelBody({ class: className, children, ...rest }: PanelBodyProps) {
    const classes = ["govuk-panel__body", className ?? ""].filter(Boolean).join(" ");

    return (
        <div className={classes} {...rest}>
            {children}
        </div>
    );
}
