// packages/react/src/phase-banner/PhaseBannerText.tsx
import { ReactNode } from 'react';

type PhaseBannerTextProps = {
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function PhaseBannerText({ class: className, children, ...rest }: PhaseBannerTextProps) {
    const classes = ["govuk-phase-banner__text", className ?? ""].filter(Boolean).join(" ");

    return (
        <span className={classes} {...rest}>
            {children ?? ""}
        </span>
    );
}

// packages/solid/src/phase-banner/PhaseBannerText.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type PhaseBannerTextProps = {
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function PhaseBannerText(props: PhaseBannerTextProps) {
    const [local, rest] = splitProps(props, ["class", "children"]);
    const classes = () =>
        ["govuk-phase-banner__text", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <span class={classes()} {...rest}>
            {local.children ?? ""}
        </span>
    );
}
