// packages/react/src/character-count/CharacterCount.tsx
type CharacterCountProps = {
    class?: string;
    [key: string]: unknown;
};

export default function CharacterCount({ class: className, ...rest }: CharacterCountProps) {
    const classes = ["govuk-textarea govuk-js-character-count", className ?? ""].filter(Boolean).join(" ");

    return (
        <textarea className={classes} {...rest}></textarea>
    );
}

// packages/svelte/src/character-count/CharacterCount.svelte
<script lang="ts">
    import type { HTMLTextareaAttributes } from "svelte/elements";

    type Props = HTMLTextareaAttributes & {
        class?: string;
    };

    let { class: className = "", value, ...rest }: Props = $props();

    let classes = $derived(
        ["govuk-textarea govuk-js-character-count", className]
            .filter(Boolean)
            .join(" "),
    );
</script>

<textarea class={classes} {...rest}>{value ?? ""}</textarea>
