// packages/solid/src/modal/ModalTitle.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type ModalTitleProps = JSX.IntrinsicElements["h2"] & {
    class?: string;
    children?: JSX.Element;
};

export default function ModalTitle(props: ModalTitleProps) {
    const [local, rest] = splitProps(props, ["class", "children"]);
    const classes = () =>
        ["govuk-heading-m", "iai-modal__title", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <h2 class={classes()} {...rest}>
            {local.children}
        </h2>
    );
}

// packages/react/src/modal/ModalTitle.tsx
import type { ComponentPropsWithoutRef, ReactNode } from "react";

type ModalTitleProps = ComponentPropsWithoutRef<"h2"> & {
    class?: string;
    children?: ReactNode;
};

export default function ModalTitle({ class: className, children, ...rest }: ModalTitleProps) {
    const classes = ["govuk-heading-m", "iai-modal__title", className ?? ""]
        .filter(Boolean)
        .join(" ");

    return (
        <h2 className={classes} {...rest}>
            {children}
        </h2>
    );
}
