// packages/solid/src/modal/ModalFooter.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type ModalFooterProps = JSX.IntrinsicElements["div"] & {
    class?: string;
    children?: JSX.Element;
};

export default function ModalFooter(props: ModalFooterProps) {
    const [local, rest] = splitProps(props, ["class", "children"]);
    const classes = () =>
        ["iai-modal__footer", "govuk-button-group", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <div class={classes()} {...rest}>
            {local.children}
        </div>
    );
}

// packages/react/src/modal/ModalFooter.tsx
import type { ComponentPropsWithoutRef, ReactNode } from "react";

type ModalFooterProps = ComponentPropsWithoutRef<"div"> & {
    class?: string;
    children?: ReactNode;
};

export default function ModalFooter({ class: className, children, ...rest }: ModalFooterProps) {
    const classes = ["iai-modal__footer", "govuk-button-group", className ?? ""]
        .filter(Boolean)
        .join(" ");

    return (
        <div className={classes} {...rest}>
            {children}
        </div>
    );
}
