// packages/react/src/modal/ModalBody.tsx
import type { ComponentPropsWithoutRef, ReactNode } from "react";

type ModalBodyProps = ComponentPropsWithoutRef<"div"> & {
    class?: string;
    children?: ReactNode;
};

export default function ModalBody({ class: className, children, ...rest }: ModalBodyProps) {
    const classes = ["iai-modal__body", className ?? ""].filter(Boolean).join(" ");

    return (
        <div className={classes} {...rest}>
            {children}
        </div>
    );
}

// packages/solid/src/modal/ModalBody.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type ModalBodyProps = JSX.IntrinsicElements["div"] & {
    class?: string;
    children?: JSX.Element;
};

export default function ModalBody(props: ModalBodyProps) {
    const [local, rest] = splitProps(props, ["class", "children"]);
    const classes = () => ["iai-modal__body", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <div class={classes()} {...rest}>
            {local.children}
        </div>
    );
}
