// packages/react/src/radios/RadioLabel.tsx
import { ReactNode } from 'react';

type RadioLabelProps = {
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function RadioLabel({ class: className, children, ...rest }: RadioLabelProps) {
    const classes = ["govuk-label govuk-radios__label", className ?? ""].filter(Boolean).join(" ");

    return (
        <label className={classes} {...rest}>
            {children ?? ""}
        </label>
    );
}

// packages/solid/src/radios/RadioLabel.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type RadioLabelProps = {
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function RadioLabel(props: RadioLabelProps) {
    const [local, rest] = splitProps(props, ["class", "children"]);
    const classes = () =>
        ["govuk-label govuk-radios__label", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <label class={classes()} {...rest}>
            {local.children ?? ""}
        </label>
    );
}
