// packages/react/src/radios/RadioInput.tsx
import type { ComponentPropsWithoutRef } from 'react';

type RadioInputProps = ComponentPropsWithoutRef<'input'> & {
    class?: string;
};

export default function RadioInput({ class: className, ...rest }: RadioInputProps) {
    const classes = ["govuk-radios__input", className ?? ""].filter(Boolean).join(" ");

    return (
        <input className={classes} type="radio" {...rest} />
    );
}

// packages/svelte/src/radios/RadioInput.svelte
<script lang="ts">
    import type { HTMLInputAttributes } from "svelte/elements";

    type Props = HTMLInputAttributes & {
        class?: string;
    };

    let { class: className = "", ...rest }: Props = $props();

    let classes = $derived(
        ["govuk-radios__input", className].filter(Boolean).join(" "),
    );
</script>

<input class={classes} type="radio" {...rest} />
