// packages/svelte/src/summary-card/SummaryCardAction.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import type { HTMLLiAttributes } from "svelte/elements";

    type Props = HTMLLiAttributes & {
        class?: string;
        children?: Snippet;
    };

    let { class: className = "", children, ...rest }: Props = $props();

    let classes = $derived(["govuk-summary-card__action", className].filter(Boolean).join(" "));
</script>

<li class={classes} {...rest}>
    {@render children?.()}
</li>

// packages/react/src/summary-card/SummaryCardAction.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react';

type SummaryCardActionProps = ComponentPropsWithoutRef<'li'> & {
    class?: string;
    children?: ReactNode;
};

export default function SummaryCardAction({ class: className, children, ...rest }: SummaryCardActionProps) {
    const classes = ["govuk-summary-card__action", className ?? ""].filter(Boolean).join(" ");

    return (
        <li className={classes} {...rest}>
            {children ?? ""}
        </li>
    );
}
