// packages/svelte/src/contents-panel/ContentsPanelListHeading.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import type { HTMLAttributes } from "svelte/elements";

    type Props = HTMLAttributes<HTMLHeadingElement> & {
        class?: string;
        children?: Snippet;
    };

    let { class: className = "", children, ...rest }: Props = $props();

    let classes = $derived(["contents-panel__list-heading", className].filter(Boolean).join(" "));
</script>

<h3 class={classes} {...rest}>
    {@render children?.()}
</h3>

// packages/react/src/contents-panel/ContentsPanelListHeading.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react';

type ContentsPanelListHeadingProps = ComponentPropsWithoutRef<'h3'> & {
    class?: string;
    children?: ReactNode;
};

export default function ContentsPanelListHeading({ class: className, children, ...rest }: ContentsPanelListHeadingProps) {
    const classes = ["contents-panel__list-heading", className ?? ""].filter(Boolean).join(" ");

    return (
        <h3 className={classes} {...rest}>
            {children}
        </h3>
    );
}
