// packages/solid/src/contents-panel/ContentsPanel.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type ContentsPanelProps = {
    heading?: string;
    headingId?: string;
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function ContentsPanel(props: ContentsPanelProps) {
    const [local, rest] = splitProps(props, ["heading", "headingId", "class", "children"]);
    const headingId = () => local.headingId ?? "contents-panel-heading";
    const classes = () =>
        ["contents-panel", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <nav class={classes()} aria-labelledby={headingId()} {...rest}>
            <h2 class="govuk-visually-hidden" id={headingId()}>
                {local.heading ?? "Pages in this section"}
            </h2>
            {local.children}
        </nav>
    );
}

// packages/react/src/contents-panel/ContentsPanel.tsx
import { ReactNode } from 'react';

type ContentsPanelProps = {
    heading?: string;
    headingId?: string;
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function ContentsPanel({
    heading = "Pages in this section",
    headingId = "contents-panel-heading",
    class: className,
    children,
    ...rest
}: ContentsPanelProps) {
    const classes = ["contents-panel", className ?? ""].filter(Boolean).join(" ");

    return (
        <nav className={classes} aria-labelledby={headingId} {...rest}>
            <h2 className="govuk-visually-hidden" id={headingId}>
                {heading}
            </h2>
            {children}
        </nav>
    );
}
