// packages/svelte/src/contents-panel/ContentsPanelList.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import type { HTMLAttributes } from "svelte/elements";

    type Props = HTMLAttributes<HTMLUListElement> & {
        class?: string;
        children?: Snippet;
    };

    let { class: className = "", children, ...rest }: Props = $props();

    let classes = $derived(["contents-panel__list", className].filter(Boolean).join(" "));
</script>

<ul class={classes} {...rest}>
    {@render children?.()}
</ul>

// packages/react/src/contents-panel/ContentsPanelList.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react';

type ContentsPanelListProps = ComponentPropsWithoutRef<'ul'> & {
    class?: string;
    children?: ReactNode;
};

export default function ContentsPanelList({ class: className, children, ...rest }: ContentsPanelListProps) {
    const classes = ["contents-panel__list", className ?? ""].filter(Boolean).join(" ");

    return (
        <ul className={classes} {...rest}>
            {children}
        </ul>
    );
}
