// packages/solid/src/contents-panel/ContentsPanelItem.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type ContentsPanelItemProps = {
    href?: string;
    current?: boolean;
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function ContentsPanelItem(props: ContentsPanelItemProps) {
    const [local, rest] = splitProps(props, ["href", "current", "class", "children"]);
    const itemClasses = () =>
        [
            "contents-panel__section-item",
            local.current ? "contents-panel__section-item--current" : "",
            local.class ?? "",
        ]
            .filter(Boolean)
            .join(" ");

    return (
        <li class={itemClasses()} {...rest}>
            <a
                class="contents-panel__link govuk-link govuk-link--no-visited-state govuk-link--no-underline"
                href={local.href}
                aria-current={local.current ? "page" : undefined}
            >
                {local.children}
            </a>
        </li>
    );
}

// packages/react/src/contents-panel/ContentsPanelItem.tsx
import { ReactNode } from 'react';

type ContentsPanelItemProps = {
    href?: string;
    current?: boolean;
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function ContentsPanelItem({
    href,
    current = false,
    class: className,
    children,
    ...rest
}: ContentsPanelItemProps) {
    const itemClasses = [
        "contents-panel__section-item",
        current ? "contents-panel__section-item--current" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <li className={itemClasses} {...rest}>
            <a
                className="contents-panel__link govuk-link govuk-link--no-visited-state govuk-link--no-underline"
                href={href}
                aria-current={current ? "page" : undefined}
            >
                {children}
            </a>
        </li>
    );
}
