// packages/react/src/panel/Panel.tsx
import { ReactNode } from 'react';

type PanelProps = {
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function Panel({ class: className, children, ...rest }: PanelProps) {
    const isInterruption = (className ?? "").includes("govuk-panel--interruption");
    const classes = [
        "govuk-panel",
        isInterruption ? "" : "govuk-panel--confirmation",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <div className={classes} {...rest}>
            {children}
        </div>
    );
}

// packages/solid/src/panel/Panel.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type PanelProps = {
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function Panel(props: PanelProps) {
    const [local, rest] = splitProps(props, ["class", "children"]);
    const classes = () => {
        const isInterruption = (local.class ?? "").includes("govuk-panel--interruption");
        return [
            "govuk-panel",
            isInterruption ? "" : "govuk-panel--confirmation",
            local.class ?? "",
        ]
            .filter(Boolean)
            .join(" ");
    };

    return (
        <div class={classes()} {...rest}>
            {local.children}
        </div>
    );
}
