// packages/react/src/panel/PanelTitle.tsx
import { ReactNode } from 'react';

type PanelTitleProps = {
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function PanelTitle({ class: className, children, ...rest }: PanelTitleProps) {
    const classes = ["govuk-panel__title", className ?? ""].filter(Boolean).join(" ");

    return (
        <h1 className={classes} {...rest}>
            {children}
        </h1>
    );
}

// packages/solid/src/panel/PanelTitle.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type PanelTitleProps = {
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function PanelTitle(props: PanelTitleProps) {
    const [local, rest] = splitProps(props, ["class", "children"]);
    const classes = () =>
        ["govuk-panel__title", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <h1 class={classes()} {...rest}>
            {local.children}
        </h1>
    );
}
