// packages/solid/src/label/Label.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type LabelProps = {
    size?: "small" | "medium" | "large" | "xl";
    isPageHeading?: boolean;
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function Label(props: LabelProps) {
    const [local, rest] = splitProps(props, ["size", "isPageHeading", "class", "children"]);
    const classes = () =>
        [
            "govuk-label",
            ({ "small": "govuk-label--s", "medium": "govuk-label--m", "large": "govuk-label--l", "xl": "govuk-label--xl" }[local.size] ?? ""),
            local.class ?? "",
        ]
            .filter(Boolean)
            .join(" ");

    const label = (
        <label class={classes()} {...rest}>
            {local.children ?? ""}
        </label>
    );

    return local.isPageHeading ? (
        <h1 class="govuk-label-wrapper">{label}</h1>
    ) : (
        label
    );
}

// packages/react/src/label/Label.tsx
import { ReactNode } from 'react';

type LabelProps = {
    size?: "small" | "medium" | "large" | "xl";
    isPageHeading?: boolean;
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function Label({ size, isPageHeading = false, class: className, children, ...rest }: LabelProps) {
    const classes = [
        "govuk-label",
        ({ "small": "govuk-label--s", "medium": "govuk-label--m", "large": "govuk-label--l", "xl": "govuk-label--xl" }[size] ?? ""),
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const label = (
        <label className={classes} {...rest}>
            {children ?? ""}
        </label>
    );

    if (isPageHeading) {
        return <h1 className="govuk-label-wrapper">{label}</h1>;
    }

    return label;
}
