// packages/react/src/summary-card/SummaryCardActions.tsx
import { ReactNode } from 'react';

type SummaryCardActionsProps = {
    /** Render as a single-action wrapper (`<div>`) instead of a list (`<ul>`).
     *  govuk uses a div for exactly one action and a ul for multiple. */
    single?: boolean;
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function SummaryCardActions({ single, class: className, children, ...rest }: SummaryCardActionsProps) {
    const classes = ["govuk-summary-card__actions", className ?? ""].filter(Boolean).join(" ");

    if (single) {
        return (
            <div className={classes} {...rest}>
                {children ?? ""}
            </div>
        );
    }

    return (
        <ul className={classes} {...rest}>
            {children ?? ""}
        </ul>
    );
}

// packages/solid/src/summary-card/SummaryCardActions.tsx
/** @jsxImportSource solid-js */

import { splitProps, Show } from "solid-js";
import type { JSX } from "solid-js";

type SummaryCardActionsProps = {
    /** Render as a single-action wrapper (`<div>`) instead of a list (`<ul>`).
     *  govuk uses a div for exactly one action and a ul for multiple. */
    single?: boolean;
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function SummaryCardActions(props: SummaryCardActionsProps) {
    const [local, rest] = splitProps(props, ["single", "class", "children"]);
    const classes = () =>
        ["govuk-summary-card__actions", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <Show
            when={local.single}
            fallback={<ul class={classes()} {...rest}>{local.children ?? ""}</ul>}
        >
            <div class={classes()} {...rest}>{local.children ?? ""}</div>
        </Show>
    );
}
