// packages/react/src/language-navigation/LanguageNavigationItem.tsx
import { ReactNode } from 'react';

type LanguageNavigationItemProps = {
    href?: string;
    current?: boolean;
    lang?: string;
    dir?: string;
    /** hreflang for link items; defaults to `lang` when omitted. */
    hreflang?: string;
    /** Visually-hidden description appended to a link item. */
    languageDescriptionText?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function LanguageNavigationItem({
    href,
    current = false,
    lang,
    dir,
    hreflang,
    languageDescriptionText,
    children,
    ...rest
}: LanguageNavigationItemProps) {
    return (
        <li className="govuk-language-navigation__list-item">
            {current ? (
                <span
                    className="govuk-language-navigation__text"
                    aria-current="true"
                    lang={lang}
                    dir={dir}
                    {...rest}
                >
                    {children}
                </span>
            ) : (
                <a
                    className="govuk-language-navigation__link"
                    href={href}
                    rel="alternate"
                    lang={lang}
                    hrefLang={hreflang ?? lang}
                    dir={dir}
                    {...rest}
                >
                    {children}
                    {languageDescriptionText ? (
                        <span className="govuk-visually-hidden"> {languageDescriptionText}</span>
                    ) : null}
                </a>
            )}
        </li>
    );
}

// packages/solid/src/language-navigation/LanguageNavigationItem.tsx
/** @jsxImportSource solid-js */

import { splitProps, Show } from "solid-js";
import type { JSX } from "solid-js";

type LanguageNavigationItemProps = {
    href?: string;
    current?: boolean;
    lang?: string;
    dir?: "ltr" | "rtl" | "auto";
    hreflang?: string;
    languageDescriptionText?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function LanguageNavigationItem(props: LanguageNavigationItemProps) {
    const [local, rest] = splitProps(props, [
        "href",
        "current",
        "lang",
        "dir",
        "hreflang",
        "languageDescriptionText",
        "children",
    ]);

    return (
        <li class="govuk-language-navigation__list-item">
            <Show
                when={local.current}
                fallback={
                    <a
                        class="govuk-language-navigation__link"
                        href={local.href}
                        rel="alternate"
                        lang={local.lang}
                        hreflang={local.hreflang ?? local.lang}
                        dir={local.dir}
                        {...rest}
                    >
                        {local.children}
                        <Show when={local.languageDescriptionText}>
                            <span class="govuk-visually-hidden"> {local.languageDescriptionText}</span>
                        </Show>
                    </a>
                }
            >
                <span
                    class="govuk-language-navigation__text"
                    aria-current="true"
                    lang={local.lang}
                    dir={local.dir}
                    {...rest}
                >
                    {local.children}
                </span>
            </Show>
        </li>
    );
}
