// packages/react/src/language-navigation/LanguageNavigationItem.tsx
import { ReactNode } from 'react';

type LanguageNavigationItemProps = {
    href?: string;
    current?: boolean;
    lang?: string;
    dir?: string;
    /** hreflang for link items; defaults to `lang` when omitted. */
    hreflang?: string;
    /** Visually-hidden description appended to a link item. */
    languageDescriptionText?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function LanguageNavigationItem({
    href,
    current = false,
    lang,
    dir,
    hreflang,
    languageDescriptionText,
    children,
    ...rest
}: LanguageNavigationItemProps) {
    return (
        <li className="govuk-language-navigation__list-item">
            {current ? (
                <span
                    className="govuk-language-navigation__text"
                    aria-current="true"
                    lang={lang}
                    dir={dir}
                    {...rest}
                >
                    {children}
                </span>
            ) : (
                <a
                    className="govuk-language-navigation__link"
                    href={href}
                    rel="alternate"
                    lang={lang}
                    hrefLang={hreflang ?? lang}
                    dir={dir}
                    {...rest}
                >
                    {children}
                    {languageDescriptionText ? (
                        <span className="govuk-visually-hidden"> {languageDescriptionText}</span>
                    ) : null}
                </a>
            )}
        </li>
    );
}

// packages/svelte/src/language-navigation/LanguageNavigationItem.svelte
<script>
    let {
        href,
        current = false,
        lang,
        dir,
        hreflang,
        languageDescriptionText,
        children,
        ...rest
    } = $props();
</script>

<li class="govuk-language-navigation__list-item">
    {#if current}
        <span class="govuk-language-navigation__text" aria-current="true" {lang} {dir} {...rest}>
            {@render children?.()}
        </span>
    {:else}
        <a
            class="govuk-language-navigation__link"
            {href}
            rel="alternate"
            {lang}
            hreflang={hreflang ?? lang}
            {dir}
            {...rest}
        >
            {@render children?.()}{#if languageDescriptionText}<span class="govuk-visually-hidden"> {languageDescriptionText}</span>{/if}
        </a>
    {/if}
</li>
