// packages/react/src/exit-this-page/ExitThisPage.tsx
import type { ComponentPropsWithoutRef, ReactNode } from 'react';

type ExitThisPageProps = ComponentPropsWithoutRef<'div'> & {
    redirectUrl?: string;
    id?: string;
    class?: string;
    children?: ReactNode;
};

export default function ExitThisPage({
    redirectUrl = 'https://www.bbc.co.uk/weather',
    id,
    class: className,
    children,
    ...rest
}: ExitThisPageProps) {
    const classes = ['govuk-exit-this-page', className ?? ''].filter(Boolean).join(' ');

    return (
        <div id={id} className={classes} data-module="govuk-exit-this-page" {...rest}>
            <a
                href={redirectUrl}
                role="button"
                draggable="false"
                className="govuk-button govuk-button--warning govuk-exit-this-page__button govuk-js-exit-this-page-button"
                data-module="govuk-button"
                rel="nofollow noreferrer"
            >
                {children ? (
                    children
                ) : (
                    <>
                        <span className="govuk-visually-hidden">Emergency</span> Exit this page
                    </>
                )}
            </a>
        </div>
    );
}

// packages/svelte/src/exit-this-page/ExitThisPage.svelte
<script>
    let {
        redirectUrl = "https://www.bbc.co.uk/weather",
        id,
        class: className = "",
        children,
        ...rest
    } = $props();

    let classes = $derived(
        ["govuk-exit-this-page", className].filter(Boolean).join(" "),
    );
</script>

<div {id} class={classes} data-module="govuk-exit-this-page" {...rest}>
    <a
        href={redirectUrl}
        role="button"
        draggable="false"
        class="govuk-button govuk-button--warning govuk-exit-this-page__button govuk-js-exit-this-page-button"
        data-module="govuk-button"
        rel="nofollow noreferrer"
    >
        {#if children}{@render children()}{:else}<span class="govuk-visually-hidden">Emergency</span> Exit this page{/if}
    </a>
</div>
