// packages/react/src/contents-panel/ContentsPanelList.tsx
import { ReactNode } from 'react';

type ContentsPanelListProps = {
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function ContentsPanelList({ class: className, children, ...rest }: ContentsPanelListProps) {
    const classes = ["contents-panel__list", className ?? ""].filter(Boolean).join(" ");

    return (
        <ul className={classes} {...rest}>
            {children}
        </ul>
    );
}

// packages/solid/src/contents-panel/ContentsPanelList.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type ContentsPanelListProps = {
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function ContentsPanelList(props: ContentsPanelListProps) {
    const [local, rest] = splitProps(props, ["class", "children"]);
    const classes = () =>
        ["contents-panel__list", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <ul class={classes()} {...rest}>
            {local.children}
        </ul>
    );
}
