// packages/react/src/feedback/Feedback.tsx
import { ReactNode } from 'react';

type FeedbackProps = {
    title?: string;
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function Feedback({ title, class: className, children, ...rest }: FeedbackProps) {
    const classes = ["govuk-feedback govuk-width-container", className ?? ""]
        .filter(Boolean)
        .join(" ");

    return (
        <div className={classes} {...rest}>
            <div className="govuk-grid-row">
                <div className="govuk-grid-column-two-thirds">
                    <h2 className="govuk-feedback__title">{title}</h2>
                    {children != null && children !== "" ? (
                        <div className="govuk-feedback__body">{children}</div>
                    ) : null}
                </div>
            </div>
        </div>
    );
}

// packages/solid/src/feedback/Feedback.tsx
/** @jsxImportSource solid-js */

import { splitProps, Show } from "solid-js";
import type { JSX } from "solid-js";

type FeedbackProps = {
    title?: string;
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function Feedback(props: FeedbackProps) {
    const [local, rest] = splitProps(props, ["title", "class", "children"]);
    const classes = () =>
        ["govuk-feedback govuk-width-container", local.class ?? ""]
            .filter(Boolean)
            .join(" ");

    return (
        <div class={classes()} {...rest}>
            <div class="govuk-grid-row">
                <div class="govuk-grid-column-two-thirds">
                    <h2 class="govuk-feedback__title">{local.title}</h2>
                    <Show when={local.children}>
                        <div class="govuk-feedback__body">{local.children}</div>
                    </Show>
                </div>
            </div>
        </div>
    );
}
