// packages/solid/src/language-navigation/LanguageNavigation.tsx
/** @jsxImportSource solid-js */

import { splitProps } from "solid-js";
import type { JSX } from "solid-js";

type LanguageNavigationProps = {
    ariaLabel?: string;
    class?: string;
    children?: JSX.Element;
    [key: string]: unknown;
};

export default function LanguageNavigation(props: LanguageNavigationProps) {
    const [local, rest] = splitProps(props, ["ariaLabel", "class", "children"]);
    const classes = () =>
        ["govuk-language-navigation", local.class ?? ""].filter(Boolean).join(" ");

    return (
        <nav class={classes()} aria-label={local.ariaLabel ?? "Language"} {...rest}>
            <ul class="govuk-language-navigation__list">
                {local.children}
            </ul>
        </nav>
    );
}

// packages/react/src/language-navigation/LanguageNavigation.tsx
import { ReactNode } from 'react';

type LanguageNavigationProps = {
    ariaLabel?: string;
    class?: string;
    children?: ReactNode;
    [key: string]: unknown;
};

export default function LanguageNavigation({
    ariaLabel = "Language",
    class: className,
    children,
    ...rest
}: LanguageNavigationProps) {
    const classes = ["govuk-language-navigation", className ?? ""]
        .filter(Boolean)
        .join(" ");

    return (
        <nav className={classes} aria-label={ariaLabel} {...rest}>
            <ul className="govuk-language-navigation__list">
                {children}
            </ul>
        </nav>
    );
}
